name: crDroid_build_kernel

env:
  KERNEL_SOURCE: 'https://github.com/crdroidandroid/android_kernel_xiaomi_cepheus'
  KERNEL_SOURCE_BRANCH: '13.0'
  KERNEL_DEFCONFIG: 'cepheus_defconfig'
  KERNEL_NAME: 'crDroid-cepheus'
  
on:
#  schedule:
#    - cron: '0 0 * * 0'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      
      - name: run build script
        run: |
          echo "BUILD_TIME=$(TZ=Asia/Shanghai date "+%Y%m%d%H%M%S")" >> $GITHUB_ENV
          bash scripts/Evasi0nKernelBuildProcess.sh ${{env.KERNEL_SOURCE}} ${{env.KERNEL_SOURCE_BRANCH}} ${{env.KERNEL_DEFCONFIG}} ${{env.KERNEL_NAME}} 
      
      - name: do build
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
          sudo bash build.sh   
          
      - name: release
        uses: actions/upload-artifact@v3.1.2
        with:
          path: |
            kernel_workspace/android-kernel/out/*.zip

